"""empty message

Revision ID: 431f8ac30b63
Revises: 29b134dcb29e
Create Date: 2026-01-10 10:22:40.039716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431f8ac30b63'
down_revision = '29b134dcb29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follows_who_do_it_fkey', type_='foreignkey')
        batch_op.drop_constraint('follows_wich_one_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.drop_column('who_do_it')
        batch_op.drop_column('wich_one')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wich_one', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('who_do_it', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follows_wich_one_fkey', 'user', ['wich_one'], ['id'])
        batch_op.create_foreign_key('follows_who_do_it_fkey', 'user', ['who_do_it'], ['id'])
        batch_op.drop_column('follower_id')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###
