"""empty message

Revision ID: 893c32909b71
Revises: df8aa71d78aa
Create Date: 2026-01-10 11:21:04.774785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893c32909b71'
down_revision = 'df8aa71d78aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
