"""empty message

Revision ID: a5df0b672835
Revises: 958b6cde2603
Create Date: 2026-01-10 09:33:11.484108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5df0b672835'
down_revision = '958b6cde2603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_followed_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_follower_id_fkey', type_='foreignkey')
        batch_op.drop_column('follower_id')
        batch_op.drop_column('followed_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follower_follower_id_fkey', 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key('follower_followed_user_id_fkey', 'user', ['followed_user_id'], ['id'])

    # ### end Alembic commands ###
