"""empty message

Revision ID: c7fc6f895dc6
Revises: d4c7fc6ca683
Create Date: 2026-01-10 09:29:05.062646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fc6f895dc6'
down_revision = 'd4c7fc6ca683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_followed_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_follower_id_fkey', type_='foreignkey')
        batch_op.drop_column('followed_user_id')
        batch_op.drop_column('follower_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('followed_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follower_follower_id_fkey', 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key('follower_followed_user_id_fkey', 'user', ['followed_user_id'], ['id'])

    # ### end Alembic commands ###
