"""empty message

Revision ID: d22601612fcc
Revises: 431f8ac30b63
Create Date: 2026-01-10 10:52:21.276640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22601612fcc'
down_revision = '431f8ac30b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('follows_followed_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follows_follower_id_fkey', type_='foreignkey')
        batch_op.drop_column('follower_id')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follows_follower_id_fkey', 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key('follows_followed_id_fkey', 'user', ['followed_id'], ['id'])

    # ### end Alembic commands ###
