"""empty message

Revision ID: d4c7fc6ca683
Revises: 9590223f3d9d
Create Date: 2026-01-10 09:21:21.642881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c7fc6ca683'
down_revision = '9590223f3d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comment_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_follower_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_followed_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.drop_column('followed_user')
        batch_op.drop_column('follower')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.drop_column('nickname')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('followed_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_followed_user_fkey', 'user', ['followed_user'], ['id'])
        batch_op.create_foreign_key('follower_follower_fkey', 'user', ['follower'], ['id'])
        batch_op.drop_column('follower_id')
        batch_op.drop_column('followed_user_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_author_fkey', 'user', ['author'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
